#!/bin/bash
export OS_USERNAME=admin
export OS_PASSWORD=openstack
export OS_TENANT_NAME=admin
export OS_REGION_NAME=RegionOne
export OS_AUTH_URL=${OS_AUTH_PROTOCOL:-http}://`juju-deployer -f keystone`:5000/v2.0

echo export OS_USERNAME=admin
echo export OS_PASSWORD=openstack
echo export OS_TENANT_NAME=admin
echo export OS_REGION_NAME=RegionOne
echo export OS_AUTH_URL=$OS_AUTH_URL

